name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout latest version
      uses: actions/checkout@v4.1.0
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.2.0
    - name: Publish .NET Core Project
      run: dotnet publish realestate-blazorwasm.csproj -c Release -o release --nologo
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.9
